# Generated by Django 4.0.3 on 2022-04-03 20:13

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='check_in',
            field=models.DateTimeField(verbose_name=datetime.datetime(2022, 4, 3, 20, 13, 52, 54117, tzinfo=utc)),
        ),
    ]
