# Generated by Django 4.0.3 on 2022-04-03 19:28

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0002_booking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='check_in',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 3, 19, 28, 11, 258508, tzinfo=utc)),
        ),
    ]
